### ISSUE TITLE
Code Preview Support

### ISSUE THREAD

**Issue by Jamal1337** [fengyuanchen/previewer#1]
Hey,
absolutely cool script! I am trying to build a page builder where it is possible to enter html code in a textarea. Then I would like to use your script to preview the result in the different screen sizes.

As far as I understand your script, it generates the preview from a given URL within an a-tag. Is it somehow possible to pass html code to the script that will be rendered in the preview screen?

Thanks in advance!

**Comment by fengyuanchen** [comment]
You don't need this plugin. Just use native JavaScript API:
```js
document.body.innerHTML = 'your html code';
```
