### ISSUE TITLE
Is it possible to add new types ?

### ISSUE THREAD

**Issue by sahanjith** [fengyuanchen/previewer#2]
Hi @fengyuanchen !

This is a cool plugin and i'm using it to render a web page in different devices. i want to know is it possible to add new types previewer ? like different devices. 

'Previewer.DEFAULTS = {
    // Show the preview page directly
    // Type: Boolean
    show: false,

    // Default preview type
    // Type: String
    type: 'phone',

    // Screen widths
    // Type: Number
    phone: 480,
    tablet: 768,
    laptop: 992,
    desktop: 1200,
    galaxyS5: 360,
    Nexus5S: 412,
    Nexus6P: 412,
    iPhone5: 320,
    iPhone6: 375,
    iPhone6Plus: 414,
    iPad: 768

  };

  Previewer.TYPES = ['phone', 'tablet', 'laptop', 'desktop','galaxyS5','Nexus5S', 'Nexus6P','iPhone5','iPhone6','iPhone6Plus','iPad'];

  Previewer.setDefaults = function (options) {
    $.extend(Previewer.DEFAULTS, options);
  };

  Previewer.TEMPLATE = (
    '<div class="previewer-container">' +
      '<div class="previewer-sidebar">' +
        '<button data-dismiss="previewer" title="Close">&times;</button>' +
        '<ul class="previewer-nav">' +
          '<li><a data-preview="phone" title="Phone"><i></i></a></li>' +
          '<li><a data-preview="tablet" title="Tablet"><i></i></a></li>' +
          '<li><a data-preview="laptop" title="Laptop"><i></i></a></li>' +
          '<li><a data-preview="desktop" title="Desktop"><i></i></a></li>' +
          '<li><a data-preview="galaxyS5" title="galaxyS5"><i></i></a></li>' +
          '<li><a data-preview="phone" title="Nexus5S"><i></i></a></li>' +
          '<li><a data-preview="phone" title="Nexus6P"><i></i></a></li>' +
          '<li><a data-preview="phone" title="iPhone5"><i></i></a></li>' +
          '<li><a data-preview="phone" title="iPhone6"><i></i></a></li>' +
          '<li><a data-preview="phone" title="iPhone6Plus"><i></i></a></li>' +
          '<li><a data-preview="phone" title="iPad"><i></i></a></li>' +
        '</ul>' +
      '</div>' +
      '<div class="previewer-mainbody">' +
        '<iframe scrolling="no"></iframe>' +
      '</div>' +
    '</div>'
  );'

**Comment by fengyuanchen** [comment]
You can customize it by yourself in your own code.
